//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySecondWebsite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Person
    {
        public int PersonID { get; set; }
        [DisplayName("First Name: ")]
        [Required(ErrorMessage = "You must input a valid first name.")]
        public string FirstName { get; set; }
        [DisplayName("Last Name: ")]
        [Required(ErrorMessage = "You must input a valid last name.")]
        public string LastName { get; set; }
        [DisplayName("E-Mail: ")]
        [Required(ErrorMessage = "You must input a valid e-mail.")]
        public string Email { get; set; }        
        public string Phone { get; set; }
        public string SSN { get; set; }
        [DisplayName("Frequently Used Security Question Answer: ")]
        public string FUSQA { get; set; }
        [DisplayName("Have you heard of lord Xenu?")]
        public string Xenu { get; set; }
        [Required(ErrorMessage = "You must select a level of devotion.")]
        [DisplayName("What is your level of devotion?")]
        public string Devotion { get; set; }
        [DisplayName("What percentage of your time could you devote to (not)Scientology?")]
        public string Percentage { get; set; }
        [DisplayName("What is your favorite color?")]
        public string Color { get; set; }
        [Required(ErrorMessage = "Password is required.")]
        [DisplayName("Please select a password: ")]
        public string Password1 { get; set; }
        [Required(ErrorMessage = "Confirmation password is required.")]
        [System.ComponentModel.DataAnnotations.Compare("Password1", ErrorMessage = "Password and confirmation password must match.")]
        [DisplayName("Enter password again to confirm: ")]
        public string Password2 { get; set; }

        public static List<SelectListItem> getItems() { 
            List<SelectListItem> items = new List<SelectListItem>() {

                new SelectListItem { Text = "Select your level of devotion: ", Value = "", Selected = true, Disabled = true},
                new SelectListItem { Text = "What is scientology", Value = "Little"},
                new SelectListItem { Text = "Could use a little auditing", Value = "Much" },
                new SelectListItem { Text = "Thetan purge incoming", Value = "Devoted"},
                new SelectListItem { Text = "Take my money L. Ron daddy", Value = "Zealot" },
            };

            return items;
        }
    }

}
